# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3e8bfa2821f7b4d1a99fb2cc612a95bd"
name = "VSBuilder"
application_url = "https://vsbuilder.techifyboost.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# scopes for your app
scopes = "write_products,write_themes,read_themes,write_content,read_content"

[auth]
redirect_urls = [
  "https://vsbuilder.techifyboost.com/auth/callback",
  "https://vsbuilder.techifyboost.com/auth/shopify/callback",
  "https://vsbuilder.techifyboost.com/api/auth/callback"
]

[pos]
embedded = false
