# This file stores configurations for your Shopify app.

name = "VSBuilder"
application_url = "https://vsbuilder.techifyboost.com"
embedded = true

[auth]
redirect_urls = [
  "https://vsbuilder.techifyboost.com/auth/callback",
  "https://vsbuilder.techifyboost.com/auth/shopify/callback",
  "https://vsbuilder.techifyboost.com/api/auth/callback"
]

[access_scopes]
# scopes for your app
scopes = "write_products,write_themes,read_themes,write_content,read_content"

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[pos]
embedded = false
